server:
  port: 8080


spring:
  profiles.active: local

kafka:
  host: localhost:9092
management:
  endpoints:
    web:
      exposure:
        include: health,info,status
---

spring:
  profiles: docker

kafka:
  host: kafka:9092
