info:
  app:
    name: omni-supimp-svc

elasticsearch:
  host: localhost
  username: geoareadataservice_v1_dev
  password: zeJDvs0EUiIz5xvCSF1KjszwFg9AXwOx
  wan-only: true
  areas-subIndexName: areas-v1
  points-subIndexName: points-v1

spring:
  profiles.active: local
  servlet.multipart.max-file-size: 500MB
  servlet.multipart.max-request-size: 500MB
  data:
    cassandra:
      geo-keyspace-name: geoareadata
      individual-keyspace-name: individual
      username: cassandra
      password: cassandra
      contact-points: localhost
      port: 9042
  rabbitmq:
    addresses: localhost
    port: 5672

logging:
  level:
    com.bisnode.omniocean.rabbit.RabbitNotifier: DEBUG

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,env,metrics

ftp:
  username: sftp-omni-ocean
  password: JRpBqChZA3Z8dxX8N7iC
  host: ftp.orange.bisnode.net
  port: 22
  ftpBasePath: omniocean/local/

server:
  port: 7474
  servlet:
    context-path: /omni-supimp-svc/v1/

service:
  verifyReports: false
  notifier:
    method: rabbit
    level: DEBUG

s3:
  bucket: testbucket
  endpoint: http://localhost:4572
  accessKey: dummy
  secretKey: dummy
#  bucket: bisnode-omni-main-dev
#  accessKey: AKIAI6N2YRSWTHB7U3OQ
#  secretKey: jYmCVplLPRe1bkDG/vwoRML22pAKl4cbQsyhZurQ
#  endpoint: s3.eu-central-1.amazonaws.com
  baseUrl: localstack/deliveries/
  baseOutputUrl: localstack/output/csv/
  pollingRate:
    milliseconds: 2000
    enabled: true

gedi:
  auth:
    host: http://localhost:7979/
    baseurl: omnimock/v1/as/token.oauth2
    username: gedi-omniocean
    password: 7oAxvP15mJjhiS8pCKmR2Pu3n9O2YuhgJ0XZ9prcivYDfazsqff4INkIyWV3XhB6
    authenticationKey: 97065fed-446d-4b03-82c9-c97618482f1f
  host: http://localhost:7979/
  baseurl: omnimock/v1/dml-gedi-s/v3/
  version: V3

featureflags:
  superImportArea: true

---

server:
  port: 7474

spring:
  profiles: localdocker
  data:
    cassandra:
      geo-keyspace-name: geoareadata
      individual-keyspace-name: individual
      username: cassandra
      password: cassandra
      contact-points: cassandra
  rabbitmq:
    addresses: rabbitmq
    port: 5672


elasticsearch:
  host: http://elasticsearch:9200
  username: geoareadataservice_v1_dev
  password: zeJDvs0EUiIz5xvCSF1KjszwFg9AXwOx
  wan-only: true

ftp:
  username: sftp-omni-ocean
  password: JRpBqChZA3Z8dxX8N7iC
  host: ftp.orange.bisnode.net
  port: 22
  ftpBasePath: omniocean/localdocker/

s3:
  bucket: testbucket
  endpoint: http://localstack:4572
  accessKey: dummy
  secretKey: dummy
#  bucket: bisnode-omni-main-dev
#  accessKey: AKIAI6N2YRSWTHB7U3OQ
#  secretKey: jYmCVplLPRe1bkDG/vwoRML22pAKl4cbQsyhZurQ
#  endpoint: s3.eu-central-1.amazonaws.com
  baseUrl: localstack/deliveries/
  baseOutputUrl: localstack/output/csv/
  pollingRate:
    milliseconds: 2000
    enabled: true


gedi:
  auth:
    host: http://wiremock:8080/
    baseurl: omnimock/v1/as/token.oauth2
    username: gedi-omniocean
    password: 7oAxvP15mJjhiS8pCKmR2Pu3n9O2YuhgJ0XZ9prcivYDfazsqff4INkIyWV3XhB6
    authenticationKey: 97065fed-446d-4b03-82c9-c97618482f1f
  host: http://wiremock:8080/
  baseurl: omnimock/v1/dml-gedi-s/v3/
  version: DEMO

service:
  verifyReports: false
  notifier:
    method: rabbit
    level: DEBUG

---

logging:
  level:
    com.bisnode.omniocean.rabbit.RabbitNotifier: INFO

server:
  port: 7474

elasticsearch:
  host: https://elasticsearch-tr.dev.aws.blue.bisnode.net
  username: geoareadataservice_v1_dev
  password: zeJDvs0EUiIz5xvCSF1KjszwFg9AXwOx
  areas-subIndexName: areas-v1
  points-subIndexName: points-v1
  wan-only: false

spring:
  profiles: aws-dev
  data:
    cassandra:
      geo-keyspace-name: omniocean_s_dev
      individual-keyspace-name: omniocean_s_dev
      username: omniocean_s_dev
      password: Eecu0ohbooth
      contact-points: cass1.dev.cluster1.blue.bisnode.net,cass2.dev.cluster1.blue.bisnode.net,cass3.dev.cluster1.blue.bisnode.net,cass4.dev.cluster1.blue.bisnode.net,cass5.dev.cluster1.blue.bisnode.net,cass6.dev.cluster1.blue.bisnode.net,cass7.dev.cluster1.blue.bisnode.net,cass8.dev.cluster1.blue.bisnode.net,cass9.dev.cluster1.blue.bisnode.net,cass10.dev.cluster1.blue.bisnode.net

  rabbitmq:
    addresses: rabbitmq1.dev.cluster1.blue.bisnode.net:5672,rabbitmq2.dev.cluster1.blue.bisnode.net:5672,rabbitmq3.dev.cluster1.blue.bisnode.net:5672
    username: omni_dev
    password: phite6huubieSh0
    virtual-host: omni_dev

s3:
  bucket: bisnode-omni-main-dev
  accessKey: AKIAI6N2YRSWTHB7U3OQ
  secretKey: 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
  endpoint: s3.eu-central-1.amazonaws.com
  baseUrl: integrationTest/deliveries/
  baseOutputUrl: integrationTest/output/csv/
  pollingRate:
    milliseconds: 4000
    enabled: true

gedi:
  auth:
    host: https://svc.dev.aws.blue.bisnode.net/
    baseurl: omnimock/v1/as/token.oauth2
    username: gedi-omniocean
    password: xqSo3uvobVokQf1zccLGofiNbmwPLkQHmMDxzmoOTqV61y6gHIUAIDV1BUz5RwVt
    authenticationKey: 97065fed-446d-4b03-82c9-c97618482f1f
  host: https://svc-dev-cluster1.blue.bisnode.net/
  baseurl: omnimock/v1/dml-gedi-s/v3/
  version: DEMO

service:
  verifyReports: false
  notifier:
    method: rabbit
    level: INFO

ftp:
  username: OM-OPQJ77
  password: iQd&FTJ9vtbm
  host: sftp.blue.bisnode.net
  port: 22
  ftpBasePath: omniocean/aws-dev/

---

server:
  port: 7474

spring:
  profiles: aws-stage
  data:
    cassandra:
      geo-keyspace-name: omniocean_s_stage
      individual-keyspace-name: omniocean_s_stage
      username: omniocean_s_stage
      password: aX6ahkei6tahc7
      contact-points: cass1.stage.cluster1.orange.bisnode.net,cass2.stage.cluster1.orange.bisnode.net,cass3.stage.cluster1.orange.bisnode.net,cass4.stage.cluster1.orange.bisnode.net,cass5.stage.cluster1.orange.bisnode.net,cass6.stage.cluster1.orange.bisnode.net,cass7.stage.cluster1.orange.bisnode.net,cass8.stage.cluster1.orange.bisnode.net,cass9.stage.cluster1.orange.bisnode.net,cass10.stage.cluster1.orange.bisnode.net
  rabbitmq:
    addresses: rabbitmq2.stage.cluster1.orange.bisnode.net:5672,rabbitmq3.stage.cluster1.orange.bisnode.net:5672,rabbitmq1.stage.cluster1.orange.bisnode.net:5672
    username: omni_stage
    password: hao9Fielahqu2Ph
    virtual-host: omni_stage

elasticsearch:
  host: https://elasticsearch-tr.stage.aws.blue.bisnode.net:9200
  username: geoareadataservice_v1_stage
  password: Y025vDSkGF1hJSxN8WQ6Fho1CwWNCOhA
  areas-subIndexName: areas-v1
  points-subIndexName: points-v1
  wan-only: false

s3:
  bucket: bisnode-omni-main-lab
  accessKey: AKIAI6N2YRSWTHB7U3OQ
  secretKey: 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
  endpoint: s3.eu-central-1.amazonaws.com
  baseUrl: deliveries/stage/
  baseOutputUrl: output/csv/
  pollingRate:
    milliseconds: 60000
    enabled: true

service:
  verifyReports: true
  notifier:
    method: log
    level: NONE

gedi:
  auth:
    host: https://qa-login.bisnode.com/
    baseurl: as/token.oauth2
    username: gedi-omniocean
    password: 7oAxvP15mJjhiS8pCKmR2Pu3n9O2YuhgJ0XZ9prcivYDfazsqff4INkIyWV3XhB6
    authenticationKey: 59924c26-b065-4689-b875-bd38fe23c676
  #    authenticationKey: d1e28022-ea1f-4c15-9920-8c1003e14e8e  QA
  host: https://svc.qa.cluster1.bisnode.net/
  baseurl: dml-gedi-s/v3/
  version: V3

---

server:
  port: 7474

spring:
  profiles: aws-prod-old
  data:
    elasticsearch:
      cluster-nodes: es1.prod.cluster1.orange.bisnode.net:9200,es2.prod.cluster1.orange.bisnode.net:9200,es3.prod.cluster1.orange.bisnode.net:9200,es4.prod.cluster1.orange.bisnode.net:9200,es5.prod.cluster1.orange.bisnode.net:9200,es6.prod.cluster1.orange.bisnode.net:9200,es7.prod.cluster1.orange.bisnode.net:9200,es8.prod.cluster1.orange.bisnode.net:9200,es9.prod.cluster1.orange.bisnode.net:9200,es10.prod.cluster1.orange.bisnode.net:9200
      cluster-name: cluster1-prod
      area-index-name: omni-geoservice-v4
      point-index-name: omni-geopoints
      wan-only: false
    cassandra:
      geo-keyspace-name: omniocean_s_prod
      individual-keyspace-name: omniocean_s_prod
      username: omniocean_s_prod
      password: eJiphi2eolief1
      contact-points: cass1.prod.cluster1.orange.bisnode.net,cass2.prod.cluster1.orange.bisnode.net,cass3.prod.cluster1.orange.bisnode.net,cass4.prod.cluster1.orange.bisnode.net,cass5.prod.cluster1.orange.bisnode.net,cass6.prod.cluster1.orange.bisnode.net,cass7.prod.cluster1.orange.bisnode.net,cass8.prod.cluster1.orange.bisnode.net,cass9.prod.cluster1.orange.bisnode.net,cass10.prod.cluster1.orange.bisnode.net
  rabbitmq:
    addresses: rabbitmq3.prod.cluster1.orange.bisnode.net:5672,rabbitmq2.prod.cluster1.orange.bisnode.net:5672
    username: omni_prod
    password: gaen8Du6shohpoo
    virtual-host: omni_prod

s3:
  bucket: bisnode-omni-datadrop
  accessKey: AKIAI5V6S5EME5DLVL2Q
  secretKey: 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
  endpoint: s3.eu-central-1.amazonaws.com
  baseUrl:
  baseOutputUrl: output/csv/
  pollingRate:
    milliseconds: 60000
    enabled: true

gedi:
  auth:
    host: https://login.bisnode.com/
    baseurl: as/token.oauth2
    username: gedi-omniocean
    password: jacKdSCVoqvstVtruhgmJcQkCsbWKsTuu1sSW9yhTC9fQ9yStYkFyMMMyBn9DDd3
    authenticationKey: cc1a9449-f05f-4f05-ac71-aa9507835913
  host: https://svc-prod-cluster1.orange.bisnode.net/
  baseurl: dml-gedi-s/v3/
  version: V3

service:
  verifyReports: false
  notifier:
    method: log
    level: NONE


featureflags:
  superImportArea: false

ftp:
  username: sftp-omni-ocean
  password: JRpBqChZA3Z8dxX8N7iC
  host: ftp.orange.bisnode.net
  port: 22
---

server:
  port: 7474

elasticsearch:
  host: https://elasticsearch-tr.prod.aws.orange.bisnode.net:9200
  username: geoareadataservice_v1_prod
  password: mLsz2ZLRC7V3UUPxrvHWJDAhqHgaUIpb
  areas-subIndexName: areas-v1
  points-subIndexName: points-v1
  wan-only: false

spring:
  profiles: aws-prod
  data:
    cassandra:
      geo-keyspace-name: omniocean_s_prod
      individual-keyspace-name: omniocean_s_prod
      username: omniocean_s_prod
      password: eJiphi2eolief1
      contact-points: cass1.prod.cluster1.orange.bisnode.net,cass2.prod.cluster1.orange.bisnode.net,cass3.prod.cluster1.orange.bisnode.net,cass4.prod.cluster1.orange.bisnode.net,cass5.prod.cluster1.orange.bisnode.net,cass6.prod.cluster1.orange.bisnode.net,cass7.prod.cluster1.orange.bisnode.net,cass8.prod.cluster1.orange.bisnode.net,cass9.prod.cluster1.orange.bisnode.net,cass10.prod.cluster1.orange.bisnode.net
  rabbitmq:
    addresses: rabbitmq3.prod.cluster1.orange.bisnode.net:5672,rabbitmq2.prod.cluster1.orange.bisnode.net:5672
    username: omni_prod
    password: gaen8Du6shohpoo
    virtual-host: omni_prod

s3:
  bucket: bisnode-omni-datadrop
  accessKey: AKIAIPELMC56SNIYGXSA
  secretKey: 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
  endpoint: s3.eu-central-1.amazonaws.com
  baseUrl:
  baseOutputUrl: output/csv/
  pollingRate:
    milliseconds: 60000
    enabled: true

gedi:
  auth:
    host: https://login.bisnode.com/
    baseurl: as/token.oauth2
    username: gedi-omniocean
    password: jacKdSCVoqvstVtruhgmJcQkCsbWKsTuu1sSW9yhTC9fQ9yStYkFyMMMyBn9DDd3
    authenticationKey: cc1a9449-f05f-4f05-ac71-aa9507835913
  host: https://svc-prod-cluster1.orange.bisnode.net/
  baseurl: dml-gedi-s/v3/
  version: V3

service:
  verifyReports: false
  notifier:
    method: log
    level: NONE

featureflags:
  superImportArea: false

ftp:
  username: sftp-omni-ocean
  password: JRpBqChZA3Z8dxX8N7iC
  host: ftp.orange.bisnode.net
  port: 22
  ftpBasePath: omniocean/prod/