version: '3'
services:
  kafka:
    image: landoop/fast-data-dev
    ports:
    - "2181:2181"
    - "3030:3030"
    - "8081:8081"
    - "8082:8082"
    - "8083:8083"
    - "9092:9092"
    environment:
      ADV_HOST: localhost
      ZK_PORT: 2181
      WEB_PORT: 3030
      REGISTRY_PORT: 8081
      REST_PORT: 8082
      CONNECT_PORT: 8083
      BROKER_PORT: 9092
#      AWS_ACCESS_KEY_ID: AKIAI6N2YRSWTHB7U3OQ
#      AWS_SECRET_ACCESS_KEY: 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

