version: '2'
services:
  omniapi:
    build: .
    container_name: "omniapi"
    command: dockerize -wait tcp://kafka:9092 -timeout 30s -- java -jar -Dspring.profiles.active=localdocker  -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n /data/omniapi.jar

  rabbitmq:
    image: rabbitmq:3.6.9-management
    container_name: "rabbitmq"

  wiremock:
    image: registry.bisnode.net/bisnode/omnimock-v1:latest-master
    container_name: "wiremock"

  kafka:
    image: landoop/fast-data-dev
    container_name: "kafka"
    environment:
      ADV_HOST: kafka
      ZK_PORT: 2181
      WEB_PORT: 3030
      REGISTRY_PORT: 8081
      REST_PORT: 8082
      CONNECT_PORT: 8083
      BROKER_PORT: 9092

networks:
  default:
    external:
      name: omni-net

