version: '2'
services:
  omniapi:
    build: .
    network_mode: "bridge"
    ports:
        - "7474:7878"
        - "8000:8000"
    depends_on:
        - kafka
    links:
        - rabbitmq
        - wiremock
        - kafka
        - zookeeper
#        - kafka-manager
    command: dockerize -wait tcp://kafka:9092 -timeout 30s -- java -jar -Dspring.profiles.active=localdocker  -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n /data/omniapi.jar

  rabbitmq:
    image: rabbitmq:3.6.9-management
    network_mode: "bridge"
    ports:
        - "5672:5672"
        - "15672:15672"

  wiremock:
    image: registry.bisnode.net/bisnode/omnimock-v1:latest-master
    network_mode: "bridge"
    ports:
      - "7979:8080"

#  kafka:
#    image: spotify/kafka
#    hostname: kafka
#    network_mode: "bridge"
#    environment:
##      ADVERTISED_HOST: kafka #Use kafka when building on bamboo
##      ADVERTISED_PORT: 9092
#      ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#    ports:
#    - "9092:9092"
#    - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    network_mode: "bridge"
    environment:
      #      KAFKA_ADVERTISED_HOST_NAME: kafka
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      #      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094,LOCALDOCKER://localhost:29092
      #      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094,LOCALDOCKER://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,LOCALDOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      #      KAFKA_ADVERTISED_LISTENERS: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    links:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: "bridge"
    ports:
    - "2181:2181"


#  kafka:
#    image: landoop/fast-data-dev
#    hostname: kafka
#    ports:
#      - "9092:9092"
#      - "3030:3030"
#    environment:
#      ADV_HOST: localhost
#      ZK_PORT: 2181
#      WEB_PORT: 3030
#      REGISTRY_PORT: 8081
#      REST_PORT: 8082
#      CONNECT_PORT: 8083
#      BROKER_PORT: 9092
#    network_mode: "bridge"

#  kafka-manager:
#    image: sheepkiller/kafka-manager
#    hostname: kafka-manager
#    network_mode: "bridge"
#    ports:
#      - "4190:9000"
#    environment:
#      ZK_HOSTS: kafka:2181
#      KAFKA: kafka:9092
#      APPLICATION_SECRET: letmein
#    depends_on:
#      - kafka
#    links:
#      - kafka
